[package]
name = "fn"
version = "0.1.0"
edition = "2021"
description = "A tool for evaluating a JavaScript function and printing the result."
license = "MIT"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
v8 = "130.0.5"
